### ISSUE TITLE
[Qt Interface] Missing transparencies with controller...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [rob-ack/yabause#15]
When you push a button, missing transparencies : 

![image](https://user-images.githubusercontent.com/12481242/132487312-9fc02e77-0297-4cc5-be07-2dbe12c83e33.png)

![image](https://user-images.githubusercontent.com/12481242/132487393-c32795d3-092c-4907-98cf-68daccbe67c9.png)

**Comment by rob-ack** [comment]
Can you give a bit more detail about what the actual problem is and what a solution should look like.
I see that in your second picture there is a icon with missing transparency but ive not seen something like that so far.

**Comment by BenjaminSiskoo** [comment]
We should see A button and not the arrow with a white background :)

**Comment by rob-ack** [comment]
Can you pls make a simple gif with a tool like [screentogif](https://www.screentogif.com/). i was not able to reproduce this behavior.

**Comment by BenjaminSiskoo** [comment]
https://www.youtube.com/watch?v=Y3J-B7wdyyE

**Comment by BenjaminSiskoo** [comment]
With Yaba Shanshiro : 

![image](https://user-images.githubusercontent.com/12481242/132940279-f68e7b5b-64fb-4ccb-a085-d7fbfc36787f.png)

**Comment by BenjaminSiskoo** [comment]
Tested with https://github.com/FCare/Kronos

**Comment by BenjaminSiskoo** [comment]
With your fork : https://github.com/rob-ack/yabause/commit/2d932d83fe76554442752fa1e15a88cf2754cd71
