### ISSUE TITLE
[Qt Interface] Kronos may crush a ROM cartdrige with a backup RAM...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [rob-ack/yabause#16]
- In the settings menu, select "16 Mbit ROMt"dans Cart/Memory>Cartridge.
- Choose the path of the Cartdrige ROM.
- Change te cartridge type to "4 MBit backup RAM". The path still the same.
- Press OK et launch the emulation.
- Close Kronos.
- the size of the rom goes from 2 Mo to 512 ko.

**Comment by rob-ack** [comment]
confirmed. is actually working like presented to the user but may not be what the user would want.

I also see the problem that this can override an existing RAM.
And a ROM should never be overridden with a RAM.

This is also a braking change in case the user has setup a path and depending on what setup is used.
If we change the path evaluation logic the setups break.

So the question now is what the user would expect here? and what we should do and what our options would be?

I think we should separate stored paths from currently one entry into at least 3 entries (STV, ROM, RAM).
As it will not solve the problem when changing the RAM size we would also need to introduce a warning (if it will resolve in data loss which i still have to confirm).

@FCare @BenjaminSiskoo: I can solve this like proposed. Any objections?

**Comment by fafling** [comment]
Currently, switching between backup cartridge ram sizes without changing the file path wipes the file.

So I think it would be better to keep track of a path for each type of cartridge that needs one. Each size of backup ram cartridge is a different type and should have its own path.

When the user selects a cartridge that have no path set, the path displayed should be empty.

**Comment by BenjaminSiskoo** [comment]
@rob-ack Perfect idea :)

**Comment by rob-ack** [comment]
I implemented separate paths for each cartridge type and a user prompt to choose a path when a cartridge path is not there.
It also cleans the path if the cartridge does not need one and proposes path names to the user when prompting.
All this should help the user a lot with this feature without restricting him in any way.

**Comment by BenjaminSiskoo** [comment]
great :)

**Comment by rob-ack** [comment]
merged https://github.com/FCare/Kronos/pull/1156
