### ISSUE TITLE
[Qt Interface - Sound] Mute button and freeze...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [rob-ack/yabause#18]
- Launch Kronos
- Launch a game
- Tick mute sound
- Kronos Freeze.

**Comment by rob-ack** [comment]
I can't reproduce this. i tried 2 games so far but i have no freeze

**Comment by BenjaminSiskoo** [comment]
Here a short video : 

https://www.youtube.com/watch?v=j0ZEHkKCUeM

**Comment by BenjaminSiskoo** [comment]
Tested with https://github.com/FCare/Kronos

**Comment by rob-ack** [comment]
confirm regression on FCare version. fix for FCare on the way

**Comment by rob-ack** [comment]
packport to kronos in https://github.com/FCare/Kronos/pull/1144
